### ISSUE TITLE
Tiles do not align correctly

### ISSUE THREAD

**Issue by jakubpawlina** [fossasia/labyrinth#1015]
## Expected Behavior

Correctly aligned tiles in labyrinth (for all labyrinth).

## Current Behavior

In many rooms tiles do not allign correctly.
![zrzut ekranu 135](https://user-images.githubusercontent.com/29257057/49698526-64055400-fbc5-11e8-882d-1071e4fce1ba.png)

## Possible Solution

Changed the way of displaying tiles in rooms

## Steps to Reproduce (for bugs)

Visit the [official website](http://labyrinth-live.surge.sh/) and go to a few rooms

## Context

It doesn't look good.

## Your Environment

* Browser Name and version: Google Chrome version 71.0.3578.80 (official) (64-bit)

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/60192890-55764580-9854-11e9-91ae-07ff11a96f42.png)

Looks like the issue has been resolved by reverting the time resize. 
Also, the bottom intersection is kept like that (made not to intersect).

Let me explain.
The top intersection does not have any space, but the bottom has. Because the top of another tile would fit in the bottom socket.
