### ISSUE TITLE
Display Play Time

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#135]
## Would you like to work on this
Yes

**Comment by duttaditya18** [comment]
Me and @0x48piraj are working on it!

**Comment by YashKumarVerma** [comment]
I think it's always a good think to confirm before working because @naveentherocker  might be already halfway or almost complete by now. 😕 

@duttaditya18  @0x48piraj

**Comment by 0x48piraj** [comment]
Sure! @YashKumarVerma

**Comment by 0x48piraj** [comment]
Note : It's a rapid changing repository, and the task time is 3 days and I think 1  day is passed :+1: 
Also, Just see the issue, I can't figure it out.
It's not anyone's fault if the issue creator doesn't spends a single penny on explaining what he wants to solve.

#### For example : 

Issue title  : Implement a cool feature.
Body : I want to work on this.

Does this doesn't flaws the OSS laws @YashKumarVerma ?

**Comment by YashKumarVerma** [comment]
You guys decide among yourselves. I'm in if a partner needed 😋

**Comment by niccokunzmann** [comment]
Duplicate with #156

**Comment by isuruAb** [comment]
hello @niccokunzmann , why we should close this one? he made this issue 23 hours ago.

**Comment by harshit98** [comment]
@duttaditya18 @0x48piraj Naveen has already claimed the issue.

@naveentherocker Is this issue similar to #156 ? or different? Would be great if you can provide some details.

**Comment by naveentherocker** [comment]
@harshit98 Both seems to be similar.

**Comment by naveentherocker** [comment]
@harshit98 It's fine. Let them work on the Issue. I don't have any conflicts

**Comment by niccokunzmann** [comment]
@isuruAb @naveentherocker I would like to keep the issue open. But issues need to be closed to keep the repository maintainable. Therefore I need to know when the issue can be closed and what the issue is about. I decided to close this issue instead of the issue #156 because #156 has a description and follows the issue template. I know when I can close #156. This is not the case with this issue.

In general: You can work on the labyrinth without opening an issue. You can create a pull request which explains and motivates your changes so we can agree that they are useful.

Also: Coordination is not my responsibility. As a maintainer I look at the issue and the pull request, see if we can use this or it destroys future progress and then I merge. I do not judge whether it is a useful part so much.

What is useful and needed by the developers needs to be discussed in the issues. It might have been too early to close this one, I could have asked or waited longer. [They both seemed like a duplicate](https://github.com/fossasia/labyrinth/issues/156#issuecomment-355495456). But: we can re-open it as soon as this is no duplicate any more and we know that it is distinct from the other issue.

In the future to avoid this, one idea could be to write more into the issue header and follow the issue template. If you think this template is useless, we can delete it. Please file a pull request for that and clarify why it should be deleted.

One other idea: We can clarify what the process should be of opening an issue: additionally looking for duplicate issues.

What do you think?

**Comment by naveentherocker** [comment]
@niccokunzmann I agree with you.

**Comment by YashKumarVerma** [comment]
@niccokunzmann thanks for clearing out things.

**Comment by 0x48piraj** [comment]
I seriously didn't got anything out of this issue.
As @niccokunzmann know, I also added a timer couple of days before.
Also, you can see the issue https://github.com/fossasia/labyrinth/issues/140. 
I clearly mentioned that I have a plan for a feature. I was working on this only!

I'm hugely sorry that I failed to understand that this issue was similar to what I thought. :disappointed: 

> I just want to say that, **Please Please describe your issue well**, as we are from different countries and it sometimes becomes a problem to understand things.

**Comment by isuruAb** [comment]
@niccokunzmann  yes it is true. all our contributors should follow the structure of the pull request template to avoid this kind of conflicts. Yes, It is better if we can add this in to contribute.md file. Thank you for clarification.
