### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#136]

**Comment by 0x48piraj** [comment]
This can be closed @niccokunzmann :+1:

**Comment by naveentherocker** [comment]
@0x48piraj Why are you working on issues that I claimed? You have worked on all the 3 Issues of mine. Can you please give me an explanation? It seems to be unfair @niccokunzmann

**Comment by niccokunzmann** [comment]
@naveentherocker Let us look into this! I hear you like to have a place to contribute and not have other people take away what you would like to improve. If that is the case, I can understand that. Could you add a link to these three issues here, so I can better understand why you write this and so we can look for a solution together?

**Comment by naveentherocker** [comment]
Issues

- https://github.com/fossasia/labyrinth/issues/136
- https://github.com/fossasia/labyrinth/issues/135
- https://github.com/fossasia/labyrinth/issues/134

I don't have a Complaint with this as finally the required contributions have been done and Labyrinth looks great. What I want to say is  It would be fine If @0x48piraj asked proper permission from me before Working on it. Unless I don't have a problem. But I have been half done with the Solution. It's  ok I'll try to work on other new issues.

**Comment by niccokunzmann** [comment]
I see, in #134 you explicitly stated that you would like to work on this and @0x48piraj worked on this without coordinating with you.

This might be a hard problem because we do not know what people do, when they do it, ... This is due to the platform and the asynchronous communication that we can never be sure if people work something it or not.

Would you like to think about a solution?

**Comment by naveentherocker** [comment]
Let's Solve the Problem. I don't have any problem with this as the Ultimate Goal is achieved. I'll try to work on another Issue. Please ask the Contributors to follow the Best Practices. That would be fine @niccokunzmann

**Comment by niccokunzmann** [comment]
@naveentherocker I am just merging and I value your perspective. You are as much in the right to direct people to the best practices. I will if I do not forget and it is a long text. Please help :)

**Comment by naveentherocker** [comment]
Sure @niccokunzmann

**Comment by 0x48piraj** [comment]
Is this was the issue that I solved ?
Please see the reference @naveentherocker 
I even not added a footer. I added a social bar, in the center !
As many people started working on it, and started further development on my developed bar, that's why I said to close this!

**Comment by niccokunzmann** [comment]
There are the controls so we have a footer now. I think this is a footer in a way as it is on the bottom of the page. I think, 100% of the requirements of this issue are met. I would keep it closed.

**Comment by niccokunzmann** [comment]
@0x48piraj Is this an answer? We can open new issues. Might it be you would have liked not to complete an issue by @naveentherocker because you do not want to take his work without asking and you like a cooperative work experience, then I suggest you both talk in a private chat with each other about what you need and like and I am sure you can sort this out.

**Comment by 0x48piraj** [comment]
I already talked, he said carry on as I'm busy. 
I'll wait for him, for a while.
I'll be contributing in other parts, in this time duration.
Seems ok @niccokunzmann ?

**Comment by niccokunzmann** [comment]
sure.

**Comment by naveentherocker** [comment]
@0x48piraj  I don't have any conflicts. Take the Issue and continue with contributing.
