### ISSUE TITLE
UI Identity

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labyrinth#225]
### Expected results
Proper design identities, including typography (Limited to less than 2) color scheme (Header, body, background, blah blah), and logo.
### Actual results
Unclear identity and no specified color, therefore each page has uneven UI, different typography, unmatched colors, etc. Currently, the game is kind of a mess between flat design and something else.
## Would you like to work on this
Yep, as GCI task. Open to suggestion.

#### Update
Just got the basics covered;

![ui_identity](https://user-images.githubusercontent.com/32614202/34661404-0b0bd56e-f47c-11e7-95c4-b3995edec1fd.jpg)

**Comment by niccokunzmann** [comment]
I will accept this as an advanced issue, if there is 
- [ ] documentation about colors, spacing and font, background, ... you name it.
- [ ] documented style guide for creating tiles with practical advice how to do that with inkscape or other editors
- [ ] and most of the site follows the design principles (except existing tiles, that would be too much work)

Is that what you have in mind? (If yes, I will tag it otherwise, we should open a new issue and clarify how they are different.)

**Comment by Ploypiti** [comment]
@niccokunzmann Yep, I have point 1 and 3 in mind, but of course point 2 can be added.

**Comment by duttaditya18** [comment]
@Ploypiti Awesome work on the mock up! When do you think you can start working?

**Comment by Ploypiti** [comment]
@duttaditya18 Thx. I already got the doc and interface done, only point 2 remaining.

**Comment by duttaditya18** [comment]
@Ploypiti Awesome work!

**Comment by niccokunzmann** [comment]
The documentation would need to be a pull request to a markdown file. This issue will be closed one day and no-one looks at it. We can think about adding a documentation folder as it grows.

**Comment by niccokunzmann** [comment]
Adding the advanced tag as much effort flows into this.

**Comment by STEdirisuriya** [comment]
@Ploypiti nice work

**Comment by abishekvashok** [comment]
@Ploypiti is this achieved shall we close this?
