### ISSUE TITLE
Addition of mantainer list to documentation

### ISSUE THREAD

**Issue by awesometushar000** [fossasia/labyrinth#24]
Adding the list of maintainers will help to tag them when one needs help.

**Comment by niccokunzmann** [comment]
@awesometushar000 @0x48piraj Please cooperate on this one: You both like to change the same. This issue is for coordination. If you both solve the task together, you both have learned a new way of cooperation and I can approve a GCI task for both you (in case that hinders you from doing things together). Cooperation can look like this: You create a branch in one of your repositories, give the other person write access and you both push to the branch. One of you can submit a pull-request for both of you - the commits of you both turn up.

There is a maintainers' team in Fossasia for the labyrinth. If you find it, you can also write what you think the responsibility of a maintainer is and when to ask.

**Comment by 0x48piraj** [comment]
Wow! I'm currently doing this, giving write access to my `repo` and collaborating.
Thanks for your response @niccokunzmann 
I'll talk to @awesometushar000 and will deliver great results :+1: :100: 

> I found the **labyrinth** team.
