### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#375]
### Expected results

images/game/inventory/diamondBlock.png looks copied. Please add a license

### Actual results

images/game/inventory/diamondBlock.png has no license attached.

#368

**Comment by 0x48piraj** [comment]
I too think it's copied.

**Comment by amryarios** [comment]
Excerpt about the license of the image, So this picture is breaking, because it can not give a copy?
What is your opinion ?


***GUIDELINES***

These Guidelines cover the use of our Brands and our Assets. For these purposes, when we refer to:

a "Name" what we mean is the name of any one of our games, taglines, features, events, or company identity, as well as any names which are confusingly similar to the names of any of our games, taglines, features, events, or company identity;
our "Brands" what we mean is any Names and/or the related logos and distinctive characteristics of any of our Names and games;
our "Assets" what we mean is the code, software, graphics, textures, images, models, sound and audio from any of our games and any videos or screenshots taken from or our games.
These Guidelines apply in addition to and not in place of our Account Terms or End User License Agreements (EULAs). Please remember that we have always said in our EULAs that we have one major rule: do not distribute anything we've made. This means don't:

- give copies of our games to anyone else;
- make commercial use of anything we've made (including our Names, Brands, and Assets);
- try to make money from anything we've made (including our Names, Brands, and Assets); or
- let other people get access to anything we've made in a way that is unfair or unreasonable;
- unless we specifically agree to it or allow it.

These Guidelines do not change that principle but are intended to help people understand what we expect and want.

Please also check back here from time to time because we may update these guidelines and provide further guidance.

**Comment by 0x48piraj** [comment]
@amryarios Should I add it ?

**Comment by duttaditya18** [comment]
@niccokunzmann This is the official End User License Agreement of Minecraft from Mojang : https://account.mojang.com/documents/minecraft_eula

I have seen animated videos which are monetized of Minecraft using the original textures. They are all around YouTube. I don't think we should have any problems with this. I will add the license if you agree to it.

If you don't think this is right, tell me I will change this right away.

**Comment by niccokunzmann** [comment]
The license clearly states that we are not allowed to include their assets. But it should take about 15-20 minutes to create something in Inkscape that looks quite similar.

**Comment by niccokunzmann** [comment]
Why do I want to enforce this:
If we open the game for contributions of pictures and music, we have a lot of possibilities to make the game more sophisticated.
Every file that we include must be clearly licensed or it is automatically AGPL.

Also: Every version of  the game counts although it is very unlikely that people look at past versions. But just having included this file under AGPL in your repository in a commit without the license states that it is AGPL licensed which is already a rights infringement (I think "infringement" is the term I read).
So I want to be careful and see everyone include the license asap. Otherwise we can have this game taken down very fast. And that can have implications for other people, too.

**Comment by 0x48piraj** [comment]
Yes, I have seen this scenario :confounded: 

I think, we, from now on, should not merge unlicensed assets.

**Comment by niccokunzmann** [comment]
I am just a developer who is a bit more into licenses. So I can not say if we are 100% on the right track. If you like to watch/outreach some information about how to license properly that is definitely helpful.
e.g. I heard that we should put the MIT license in the credits file because this is another view of the software wihout code. 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Might be but it is not practiced widely.
