### ISSUE TITLE
Add Animated Tiles

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#40]
Try to Add many animated tiles. So that the Game will be better.

**Comment by niccokunzmann** [comment]
There is a CGI-Task to do this.
Would you like to define when this issue is completed?

**Comment by naveentherocker** [comment]
I think it's better to keep this Issue open.

**Comment by niccokunzmann** [comment]
Would you like all animated tiles to reference the issue, so they can inspire and help each other?
You could add this link to the task as a requirement in the tasks folder.

**Comment by niccokunzmann** [comment]
I am closing this to keep the issue tracker small. We have a task for this: https://github.com/fossasia/labyrinth/blob/master/tasks/create-animated-tile.md There is one animated tile and I hope to see more.
Please explain what "better" means and how it is good for the people developing this.
I will close this because I think a small issue tracker allows us to coordinate faster. As I am in search for advanced issues, I do not want to take much time scrolling through old issues with uncertain closing criteria.
