### ISSUE TITLE
Remove Squash commits from PR template?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#757]
The [Pull request template](https://github.com/fossasia/labyrinth/blob/master/.github/PULL_REQUEST_TEMPLATE.md) has a checkbox for merge commits.
Asking new contributors for squash their commits might be a burden that rejects their contributions.
It can take quite some time for people to adopt to squashing. The first contribution might be done via upload and further contributions make squashing and using git much more comfortable.
After all, the labyrinth is nothing serious but should guide newcomers to the process we use at fossasia.

My questions would be:
- would it hurt the development if we remove the squashing from the pull request templates?
- would making it optional be a way that guides beginners in the right direction?
- would it be ok to use merge-commits when we merge as maintainers?

**Comment by niccokunzmann** [comment]
@@

**Comment by niccokunzmann** [comment]
@YashKumarVerma, I would value your input here.

**Comment by YashKumarVerma** [comment]
When I first participated in GCI, whenever I was asked to squash commit, I would close the PR. Create a new one which had only one commit. Github Desktop too doens't have anything to aid the process or squashing. 

As we have a lot of young programmers in GCI, **squashing** is a hinderance to contribution. Removing the boundation of squashing will no doubt ease the work of students and foster constributions to the project, but at the same time, it might make maintaining the project a tedious task. Organized commits make it significantly easy to track changes, refer them, and most importantly, revert them (we actually reverted the game to an older state last year). A bunch of commits for a minor patch is surely something we must avoid.

Making it optional won't misguide the students, because all other projects have strict guidelines regarding PRs, Issues and Commits. On the contrary, it will encourage the students to contribute more to Labyrinth as the workflow would be fast and easy.

But there's something we must adress. ***we must ask them to squash the commits***, and if they run into errors, then omit them of the process. The maintainers can squash the commits when merged. This can be the sweet spot for both the sides. 

The students will attempt to squash the commits, and if they are unable to, we can accept the PR (**provided it doesn't have dozens of commits**). This way new contributers can throw in PRs with a couple of commits if required, and therefore focus and contribute more to the project.

**Comment by niccokunzmann** [comment]
Thanks @YashKumarVerma for taking the time!

I understand as follows:

> would it hurt the development if we remove the squashing from the pull request templates?

yes

> would making it optional be a way that guides beginners in the right direction?

Optional is not the term you would use.
The process is to

1. ask for them to merge
2. give them the time to try
3. merge the commit yourself

> would it be ok to use merge-commits when we merge as maintainers?

We can use squash and merge commits and revert pull requests. This does not really help in maintaining the project through a commit history, though.

---

My suggestion for going forward with this:

1. Add a link to what squashing means with clear instructions on how to achieve it to the [PR-tempate](https://github.com/fossasia/labyrinth/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
2. `Squashed the commits.` Should be `Tried to squash the commits`

(2) is pretty clear: We want them to try it. We see if they are successful.
Also, If this is checked, we can ask if they need help and if not, if they would like to try it.
